version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret   # root password
      MYSQL_DATABASE: skylon        # database to create automatically
      MYSQL_USER: arrowuser         # optional, non-root user
      MYSQL_PASSWORD: arrowpass     # password for the non-root user
    volumes:
      - db_data:/var/lib/mysql
      - ./skylon.sql:/docker-entrypoint-initdb.d/skylon.sql
    ports:
      - "3306:3306"

volumes:
  db_data:
